### ISSUE TITLE
依赖一大堆。。。跑起来不太容易啊

### ISSUE THREAD

**Issue by pdog18** [thepacific/banner-view#1]
Error:Could not find method baseline() for arguments [C:\Users\pdog\Desktop\banner-view-master\banner-view\demo\lint-baseline.xml] on object of type com.android.build.gradle.internal.dsl.LintOptions.

**Comment by pdog18** [comment]
Error:Failed to find Build Tools revision 26.0.0-rc1
<a href="install.build.tools">Install Build Tools 26.0.0-rc1 and sync project</a>

**Comment by pdog18** [comment]
All packages are not available for download! 
The following packages are not available:
package id build-tools 26.0.0-rc1

**Comment by hwt88** [comment]
@pdog18 能运行起来了吗？

**Comment by hwt88** [comment]
@pdog18 build tool等编译环境软件版本，你自行修改为自己本地环境就行了。
